### ISSUE TITLE
Approach for very large data?

### ISSUE THREAD

**Issue by sergeyf** [gpapadis/ContinuousFilteringBenchmark#1]
Hello,

Do you have advice on what to do for very large datasets? Let's say I have a dataset of 500 million entities and I'd like to find duplicates therein. Which of the methods that you've studied seem plausible for this case?

Thanks for the nice person and your code,
Sergey

**Comment by gpapadis** [comment]
Hi Sergey,

thanks for reaching out! I recommend using JedAI's default blocking workflow, which is described here: http://cgi.di.uoa.gr/~koubarak/publications/2020/JedAI_3D_ER.pdf, i.e., Token Blocking -> Block Purging -> Block Filtering -> Cardinality Node Pruning. This workflow ensures that the number of candidates you get depends linearly on the number of input entities. You can find the code here:
Clean-Clean ER: https://github.com/scify/JedAIToolkit/blob/master/src/test/java/org/scify/jedai/version3/DefaultConfigurationBlockingBasedWorkflowCcer.java
Dirty ER: https://github.com/scify/JedAIToolkit/blob/master/src/test/java/org/scify/jedai/version3/DefaultConfigurationBlockingBasedWorkflowDer.java
Note that you can exclude IEntityMatching and IEntityClustering, focusing only on the blocking methods. Note also that this code is the serial execution of the workflow, but for such large datasets you had better use the parallel adaptation on Apache Spark, which is available here: https://github.com/scify/JedAI-Spark . Make sure that the configurations are the same, unless you want to try to fine them (e.g., setting the ratio of Block Filtering to 0.5 instead of 0.8 for more aggressive pruning and lower run-times). 

Kind regards,
George

**Comment by sergeyf** [comment]
I appreciate your response! Please feel free to close this issue as you see fit.
